global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3002']

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:3003']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3004']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:3005']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3006']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3007']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
